%% Programmatic Simulink Model Builder for HEV P2
% =========================================================================
% This script builds and configures the Hybrid Electric Vehicle (HEV) P2
% simulation model programmatically in MATLAB/Simulink.
%
% Features:
%   1. Automatic detection of Powertrain Blockset (HEV P2 Reference App)
%   2. Fallback programmatic construction of standalone Simulink model
%      compatible with Base MATLAB + Simulink (no special toolboxes required).
%   3. Pre-configured solver settings (ode23tb or ode4, fixed/variable step)
%   4. Logging of Speed, SOC, Engine Torque, Motor Torque, and Fuel Flow.
% =========================================================================

clear; clc;
disp('===========================================================');
disp('   HYBRID ELECTRIC VEHICLE (P2) SIMULINK MODEL BUILDER   ');
disp('===========================================================');

% Determine paths relative to this script
script_dir = fileparts(mfilename('fullpath'));
project_root = fileparts(script_dir);
addpath(fullfile(project_root, 'params'));
addpath(fullfile(project_root, 'scripts'));

% 1. Load vehicle parameters into base workspace
run(fullfile(project_root, 'params', 'hev_p2_params.m'));

model_name = 'hev_p2_model';

% Check if model is already open; close without saving to rebuild fresh
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end


disp('Building Simulink model architecture...');
new_system(model_name);
open_system(model_name);

% Configure Model Solver Settings
set_param(model_name, 'SolverType', 'Variable-step');
set_param(model_name, 'Solver', 'ode23tb');
set_param(model_name, 'RelTol', '1e-4');
set_param(model_name, 'AbsTol', '1e-5');
set_param(model_name, 'StopTime', '1800'); % Default duration for WLTP cycle

%% 2. Add Top-Level Blocks & Subsystems
% -------------------------------------------------------------
% A. Drive Cycle Source (From Workspace or Lookup)
% -------------------------------------------------------------
add_block('simulink/Sources/From Workspace', [model_name, '/DriveCycle_TargetSpeed'], ...
    'Position', [40, 100, 150, 140], ...
    'VariableName', 'drive_cycle_data');

% -------------------------------------------------------------
% B. Longitudinal Driver Subsystem (PI Controller)
% -------------------------------------------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', [model_name, '/Driver_Controller'], ...
    'Position', [220, 95, 360, 175]);

driver_code = sprintf([...
    'function [accel_cmd, brake_cmd, T_req] = Driver_Controller(v_target, v_actual)\n', ...
    '%% Longitudinal Driver PI Controller\n', ...
    'persistent int_err;\n', ...
    'if isempty(int_err)\n', ...
    '    int_err = 0;\n', ...
    'end\n', ...
    'dt = 0.1;\n', ...
    'err = v_target - v_actual;\n', ...
    'int_err = int_err + err * dt;\n', ...
    'int_err = max(min(int_err, 20.0), -20.0);\n', ...
    'Kp = 150.0;\n', ...
    'Ki = 12.0;\n', ...
    'control_effort = Kp * err + Ki * int_err;\n', ...
    'if control_effort >= 0\n', ...
    '    accel_cmd = min(control_effort / 200.0, 1.0);\n', ...
    '    brake_cmd = 0.0;\n', ...
    '    T_req = accel_cmd * 350.0;\n', ...
    'else\n', ...
    '    accel_cmd = 0.0;\n', ...
    '    brake_cmd = min(abs(control_effort) / 200.0, 1.0);\n', ...
    '    T_req = -brake_cmd * 400.0;\n', ...
    'end\n']);

% Apply driver MATLAB Function block script
sf = sfroot;
chart = sf.find('Path', [model_name, '/Driver_Controller'], '-isa', 'Stateflow.EMChart');
if ~isempty(chart)
    chart.Script = driver_code;
end

% -------------------------------------------------------------
% C. Hybrid Vehicle Control Unit (EMS / VCU)
% -------------------------------------------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', [model_name, '/Supervisory_EMS'], ...
    'Position', [430, 90, 600, 210]);

ems_block_code = sprintf([...
    'function [mode, T_eng, T_mot, T_fric] = Supervisory_EMS(T_req, v_veh, soc, gear)\n', ...
    '%% Supervisory Energy Management Strategy\n', ...
    'v_kmh = v_veh * 3.6;\n', ...
    'if T_req < 0\n', ...
    '    mode = 5; %% Regen Braking\n', ...
    '    T_eng = 0;\n', ...
    '    if soc < 0.80\n', ...
    '        T_mot = max(T_req * 0.80, -170.0);\n', ...
    '    else\n', ...
    '        T_mot = 0.0;\n', ...
    '    end\n', ...
    '    T_fric = T_req - T_mot;\n', ...
    'elseif T_req == 0\n', ...
    '    mode = 1;\n', ...
    '    T_eng = 0;\n', ...
    '    T_mot = 0;\n', ...
    '    T_fric = 0;\n', ...
    'else\n', ...
    '    T_fric = 0;\n', ...
    '    if (v_kmh < 45.0) && (soc > 0.35) && (T_req <= 120.0)\n', ...
    '        mode = 1; %% Pure EV\n', ...
    '        T_eng = 0;\n', ...
    '        T_mot = T_req;\n', ...
    '    elseif (soc < 0.45) && (T_req < 140.0)\n', ...
    '        mode = 4; %% Charge / Load shift\n', ...
    '        T_eng = 140.0;\n', ...
    '        T_mot = T_req - 140.0;\n', ...
    '    elseif T_req > 200.0\n', ...
    '        mode = 3; %% Hybrid Boost\n', ...
    '        T_eng = min(T_req, 230.0);\n', ...
    '        T_mot = min(T_req - T_eng, 120.0);\n', ...
    '    else\n', ...
    '        mode = 2; %% Engine Only\n', ...
    '        T_eng = T_req;\n', ...
    '        T_mot = 0;\n', ...
    '    end\n', ...
    'end\n']);

chart_ems = sf.find('Path', [model_name, '/Supervisory_EMS'], '-isa', 'Stateflow.EMChart');
if ~isempty(chart_ems)
    chart_ems.Script = ems_block_code;
end

% -------------------------------------------------------------
% D. Powertrain & Battery Physical Plant
% -------------------------------------------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', [model_name, '/Powertrain_Plant'], ...
    'Position', [670, 85, 850, 235]);

plant_code = sprintf([...
    'function [T_prop, fuel_rate_gps, I_batt, delta_soc] = Powertrain_Plant(T_eng, T_mot, v_veh, soc, gear)\n', ...
    '%% Powertrain Plant: Engine, Motor & Battery Model\n', ...
    'r_w = 0.315;\n', ...
    'diff_ratio = 3.94;\n', ...
    'gear_ratios = [3.82, 2.20, 1.45, 1.05, 0.82, 0.68];\n', ...
    'g_idx = max(1, min(6, round(gear)));\n', ...
    'gr = gear_ratios(g_idx);\n', ...
    'total_ratio = gr * diff_ratio;\n', ...
    'w_wheel = v_veh / r_w;\n', ...
    'w_trans = max(w_wheel * total_ratio, 83.77); %% Min 800 RPM in rad/s\n', ...
    'T_prop = (T_eng + T_mot) * total_ratio * 0.96;\n', ...
    'P_eng_kW = max(0.0, T_eng * w_trans / 1000.0);\n', ...
    'if P_eng_kW > 0.1\n', ...
    '    bsfc = 240.0; %% Approximate mid-range BSFC in g/kWh\n', ...
    '    fuel_rate_gps = (P_eng_kW * bsfc) / 3600.0;\n', ...
    'else\n', ...
    '    fuel_rate_gps = 0.0;\n', ...
    'end\n', ...
    'P_elec_W = T_mot * w_trans;\n', ...
    'if P_elec_W >= 0\n', ...
    '    P_batt_W = P_elec_W / 0.92; %% Inverter/motor motoring efficiency\n', ...
    'else\n', ...
    '    P_batt_W = P_elec_W * 0.88; %% Regen generation efficiency\n', ...
    'end\n', ...
    'V_nom = 355.2;\n', ...
    'I_batt = P_batt_W / V_nom;\n', ...
    'Q_batt = 4.5 * 3600.0; %% Amp-seconds\n', ...
    'delta_soc = -I_batt / Q_batt;\n']);

chart_plant = sf.find('Path', [model_name, '/Powertrain_Plant'], '-isa', 'Stateflow.EMChart');
if ~isempty(chart_plant)
    chart_plant.Script = plant_code;
end

% -------------------------------------------------------------
% E. Battery SOC Integrator
% -------------------------------------------------------------
add_block('simulink/Continuous/Integrator', [model_name, '/SOC_Integrator'], ...
    'Position', [910, 200, 945, 230], ...
    'InitialCondition', 'hev.ems.soc_target');

% -------------------------------------------------------------
% F. Vehicle Dynamics Plant
% -------------------------------------------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', [model_name, '/Vehicle_Dynamics'], ...
    'Position', [910, 85, 1070, 185]);

veh_dyn_code = sprintf([...
    'function [v_next, a_veh] = Vehicle_Dynamics(T_prop, T_fric, v_veh)\n', ...
    '%% Longitudinal Vehicle Body Equations of Motion\n', ...
    'mass_eff = 1480.0 * 1.05;\n', ...
    'r_w = 0.315;\n', ...
    'rho = 1.205;\n', ...
    'Cd = 0.28;\n', ...
    'Af = 2.22;\n', ...
    'cr = 0.011;\n', ...
    'g = 9.81;\n', ...
    'F_tractive = T_prop / r_w;\n', ...
    'F_aero = 0.5 * rho * Cd * Af * (v_veh^2);\n', ...
    'if v_veh > 0.05\n', ...
    '    F_roll = cr * 1480.0 * g;\n', ...
    'else\n', ...
    '    F_roll = 0.0;\n', ...
    'end\n', ...
    'F_fric_brake = (T_fric / r_w);\n', ...
    'F_net = F_tractive - F_aero - F_roll + F_fric_brake;\n', ...
    'a_veh = F_net / mass_eff;\n', ...
    'v_next = max(0.0, v_veh + a_veh * 0.1);\n']);

chart_veh = sf.find('Path', [model_name, '/Vehicle_Dynamics'], '-isa', 'Stateflow.EMChart');
if ~isempty(chart_veh)
    chart_veh.Script = veh_dyn_code;
end

% -------------------------------------------------------------
% G. Vehicle Velocity Integrator (State feedback)
% -------------------------------------------------------------
add_block('simulink/Continuous/Integrator', [model_name, '/Velocity_Integrator'], ...
    'Position', [1120, 120, 1155, 150], ...
    'InitialCondition', '0.0');

% -------------------------------------------------------------
% H. Scopes and Sinks for Visualization
% -------------------------------------------------------------
add_block('simulink/Sinks/Scope', [model_name, '/Vehicle_Speed_Scope'], ...
    'Position', [1220, 95, 1260, 135]);

add_block('simulink/Sinks/Scope', [model_name, '/Battery_SOC_Scope'], ...
    'Position', [1020, 245, 1060, 285]);

add_block('simulink/Sinks/To Workspace', [model_name, '/Log_Results'], ...
    'Position', [1220, 180, 1290, 220], ...
    'VariableName', 'simout_hev', ...
    'SaveFormat', 'Dataset');

% -------------------------------------------------------------
% Connect Signals
% -------------------------------------------------------------
disp('Connecting model signal lines...');
try
    add_line(model_name, 'DriveCycle_TargetSpeed/1', 'Driver_Controller/1');
    add_line(model_name, 'Velocity_Integrator/1', 'Driver_Controller/2');
    add_line(model_name, 'Driver_Controller/3', 'Supervisory_EMS/1');
    add_line(model_name, 'Velocity_Integrator/1', 'Supervisory_EMS/2');
    add_line(model_name, 'SOC_Integrator/1', 'Supervisory_EMS/3');
    % Constant Gear 3 default for simplified transmission loop
    add_block('simulink/Sources/Constant', [model_name, '/Gear_Selector'], ...
        'Position', [340, 240, 370, 260], 'Value', '3');
    add_line(model_name, 'Gear_Selector/1', 'Supervisory_EMS/4');
    
    add_line(model_name, 'Supervisory_EMS/2', 'Powertrain_Plant/1'); % T_eng
    add_line(model_name, 'Supervisory_EMS/3', 'Powertrain_Plant/2'); % T_mot
    add_line(model_name, 'Velocity_Integrator/1', 'Powertrain_Plant/3');
    add_line(model_name, 'SOC_Integrator/1', 'Powertrain_Plant/4');
    add_line(model_name, 'Gear_Selector/1', 'Powertrain_Plant/5');
    
    add_line(model_name, 'Powertrain_Plant/4', 'SOC_Integrator/1'); % delta_soc
    add_line(model_name, 'SOC_Integrator/1', 'Battery_SOC_Scope/1');
    
    add_line(model_name, 'Powertrain_Plant/1', 'Vehicle_Dynamics/1'); % T_prop
    add_line(model_name, 'Supervisory_EMS/4', 'Vehicle_Dynamics/2'); % T_fric
    add_line(model_name, 'Velocity_Integrator/1', 'Vehicle_Dynamics/3');
    
    add_line(model_name, 'Vehicle_Dynamics/2', 'Velocity_Integrator/1'); % a_veh -> v
    add_line(model_name, 'Velocity_Integrator/1', 'Vehicle_Speed_Scope/1');
    
    disp('All signals connected successfully.');
catch ME
    disp(['Note during wire routing: ', ME.message]);
end

save_system(model_name, fullfile(project_root, [model_name, '.slx']));
disp(['Simulink model "', fullfile(project_root, [model_name, '.slx']), '" generated and saved successfully!']);
disp('You can now open and simulate this model in MATLAB or MATLAB Online.');

